apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: webdev-dev
  labels:
    group: webdev
    environment: dev
data:
  accountId: "12345"
  labels:
    group: webdev
    businessUnit: sales
  role: "role/dev-provisioner"
---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: webdev-prod
  labels:
    group: webdev
    environment: prod
data:
  accountId: "54321"
  labels:
    group: webdev
    businessUnit: sales
  role: "role/prod-provisioner"
---
apiVersion: example.crossplane.io/v1
kind: XCluster
metadata:
  name: net-staging-blue
  labels:
    type: cluster
spec:
  compositionRef:
    name: compositecluster.example.crossplane.io
  compositionSelector:
    matchLabels:
      provider: aws
  compositionUpdatePolicy: Automatic
---
apiVersion: example.crossplane.io/v1
kind: XCluster
metadata:
  name: net-staging-green
  labels:
    type: cluster
spec:
  compositionRef:
    name: compositecluster.example.crossplane.io
  compositionSelector:
    matchLabels:
      provider: aws
  compositionUpdatePolicy: Automatic
---
apiVersion: example.crossplane.io/v1
kind: XCluster
metadata:
  name: net-staging-yellow
  labels:
    type: cluster
spec:
  compositionRef:
    name: compositecluster.example.crossplane.io
  compositionSelector:
    matchLabels:
      provider: aws
  compositionUpdatePolicy: Automatic
